POST http://localhost:3000/api/players
Content-Type: application/json

{
  "firstname": "PETER",
  "lastname": "Pirker",
  "club": "Inter Miami",
  "age": 18,
  "country": "Austria"
}

###

GET http://localhost:3000/api/players/parameter?sort=des
Accept: application/json

###
GET http://localhost:3000/api/players/1
Accept: application/json

###
### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA
Accept: application/json

###
### GET request to example server
GET http://localhost:3000/api/players
Accept: application/json
###

DELETE http://localhost:3000/api/players/1
Accept: application/json